---
title: "Visualization Lab 3"
author: "Roshni Sundaramurthy (rossu809) & Brian Masinde (brima748)"
date: "26 September 2018"
output:
  html_document:
    df_print: paged
  html_notebook:
    theme: journal
  pdf_document: default
fontsize: 11pt
bibliography: references.bib
---

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
# steps 4,5, 6 use euclidean distance
library(plotly)
```

```{r data, echo = FALSE}
prices_earnings <- read.delim("prices-and-earnings.txt")
```
### Question 1.
```{r}
# keep columns 1,2,5,6,7,9,10,16,17,18,19

p_e <- prices_earnings[, c(1,2,5,6,7,9,10,16,17,18,19)]

rownames(p_e) <- p_e[[1]]
```

```{r scale, echo = FALSE}
# question 2 scaling
p_e_sc <- scale(p_e[,-1])

```

### Question 2.
Without doing any reordering We cannot identify any clusters or outliers.

```{r heatmap}
#p_e_sc %>% 
  plot_ly(x =~colnames(p_e_sc), y =~rownames(p_e_sc),
    z = ~p_e_sc, type = "heatmap", 
    colors = colorRamp(c("black","red"))
  ) %>%
  layout(title =  "Heatmap of prices and earnings",
         xaxis = list(title = "Price-Earnings Indicators", zeroline = FALSE),
         yaxis = list(title = "Cities", zeroline = FALSE)
  )
```

### Question 3.

```{r Question3_a}
# seriation needs to permute rows and columns, thus distance by row and column
p_e_rdist <- dist(p_e_sc, method = "euclidean")

p_e_cdist <- dist(t(p_e_sc), method = "euclidean")
```



```{r question3_b}
# computing distance as one minus correlation

p_e_cor <- 1 - cor(p_e_sc)

# as distance
p_e_cor_dist <- as.dist(p_e_cor)
```

```{r}

```

